# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='class.proto',
  package='class',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63lass.proto\x12\x05\x63lass\"\x1d\n\tClassList\x12\x10\n\x08\x63lass_id\x18\x01 \x03(\t\"#\n\x10\x43lassListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"\x1b\n\x07\x43lassId\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\t\"#\n\x0fIsExistResponse\x12\x10\n\x08is_exist\x18\x01 \x01(\x08\x32\xb3\x01\n\x0f\x43lassController\x12\x33\n\x04List\x12\x17.class.ClassListRequest\x1a\x10.class.ClassList\"\x00\x12\x36\n\x10GetCommonClasses\x12\x0e.class.ClassId\x1a\x10.class.ClassList\"\x00\x12\x33\n\x07IsExist\x12\x0e.class.ClassId\x1a\x16.class.IsExistResponse\"\x00\x62\x06proto3'
)




_CLASSLIST = _descriptor.Descriptor(
  name='ClassList',
  full_name='class.ClassList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_id', full_name='class.ClassList.class_id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_CLASSLISTREQUEST = _descriptor.Descriptor(
  name='ClassListRequest',
  full_name='class.ClassListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='class.ClassListRequest.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=88,
)


_CLASSID = _descriptor.Descriptor(
  name='ClassId',
  full_name='class.ClassId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_id', full_name='class.ClassId.class_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=117,
)


_ISEXISTRESPONSE = _descriptor.Descriptor(
  name='IsExistResponse',
  full_name='class.IsExistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_exist', full_name='class.IsExistResponse.is_exist', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['ClassList'] = _CLASSLIST
DESCRIPTOR.message_types_by_name['ClassListRequest'] = _CLASSLISTREQUEST
DESCRIPTOR.message_types_by_name['ClassId'] = _CLASSID
DESCRIPTOR.message_types_by_name['IsExistResponse'] = _ISEXISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassList = _reflection.GeneratedProtocolMessageType('ClassList', (_message.Message,), {
  'DESCRIPTOR' : _CLASSLIST,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:class.ClassList)
  })
_sym_db.RegisterMessage(ClassList)

ClassListRequest = _reflection.GeneratedProtocolMessageType('ClassListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLASSLISTREQUEST,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:class.ClassListRequest)
  })
_sym_db.RegisterMessage(ClassListRequest)

ClassId = _reflection.GeneratedProtocolMessageType('ClassId', (_message.Message,), {
  'DESCRIPTOR' : _CLASSID,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:class.ClassId)
  })
_sym_db.RegisterMessage(ClassId)

IsExistResponse = _reflection.GeneratedProtocolMessageType('IsExistResponse', (_message.Message,), {
  'DESCRIPTOR' : _ISEXISTRESPONSE,
  '__module__' : 'class_pb2'
  # @@protoc_insertion_point(class_scope:class.IsExistResponse)
  })
_sym_db.RegisterMessage(IsExistResponse)



_CLASSCONTROLLER = _descriptor.ServiceDescriptor(
  name='ClassController',
  full_name='class.ClassController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=157,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='class.ClassController.List',
    index=0,
    containing_service=None,
    input_type=_CLASSLISTREQUEST,
    output_type=_CLASSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCommonClasses',
    full_name='class.ClassController.GetCommonClasses',
    index=1,
    containing_service=None,
    input_type=_CLASSID,
    output_type=_CLASSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsExist',
    full_name='class.ClassController.IsExist',
    index=2,
    containing_service=None,
    input_type=_CLASSID,
    output_type=_ISEXISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSCONTROLLER)

DESCRIPTOR.services_by_name['ClassController'] = _CLASSCONTROLLER

# @@protoc_insertion_point(module_scope)
